/*
* @Author: vincetam
* @Date:   2015-10-28 19:34:07
* @Last Modified by:   vincetam
* @Last Modified time: 2016-01-02 17:14:09
*/

'use strict';

var editWorkoutConstants = {
  SET_DEFAULT_OR_CUSTOM: 'SET_DEFAULT_OR_CUSTOM',
  SET_WORKOUT: 'SET_WORKOUT',
  RESET_WORKOUT: 'RESET_WORKOUT',
  SAVE_DATE: 'SAVE_DATE',
  SET_INSTRUCTIONS: 'SET_INSTRUCTIONS',
  ADD_EXERCISE: 'ADD_EXERCISE',
  REMOVE_EXERCISE: 'REMOVE_EXERCISE',
  SET_TARGET_EXERCISE_INDEX: 'SET_TARGET_EXERCISE_INDEX',
  SAVE_EXERCISE: 'SAVE_EXERCISE',
  TOGGLE_RECORDING: 'TOGGLE_RECORDING',
  SET_RESULT_TYPE: 'SET_RESULT_TYPE',
  ADD_PART: 'ADD_PART',
  REMOVE_PART: 'REMOVE_PART',
  SET_TARGET_PART_IDX: 'SET_TARGET_PART_IDX',
  SET_PART_NAME: 'SET_PART_NAME',
  SET_RESULT_TIME: 'SET_RESULT_TIME',
  SET_RESULT_ROUNDS: 'SET_RESULT_ROUNDS',
};

module.exports = editWorkoutConstants;
