/*
* @Author: vincetam
* @Date:   2015-10-28 19:34:07
* @Last Modified by:   vincetam
* @Last Modified time: 2016-02-03 19:32:49
*/

'use strict';

var editWorkoutConstants = {
  SET_DEFAULT_OR_CUSTOM: 'SET_DEFAULT_OR_CUSTOM',
  SET_DAILY_WORKOUT: 'SET_DAILY_WORKOUT',
  SET_WORKOUT: 'SET_WORKOUT',
  SET_TO_DEFAULT_WORKOUT: 'SET_TO_DEFAULT_WORKOUT',
  RESET_WORKOUT: 'RESET_WORKOUT',
  SAVE_DATE: 'SAVE_DATE',
  SET_INSTRUCTIONS: 'SET_INSTRUCTIONS',
  ADD_EXERCISE: 'ADD_EXERCISE',
  REMOVE_EXERCISE: 'REMOVE_EXERCISE',
  SAVE_EXERCISE: 'SAVE_EXERCISE',
  SET_TARGET_PART_IDX: 'SET_TARGET_PART_IDX',
  SET_TARGET_EXERCISE_INDEX: 'SET_TARGET_EXERCISE_INDEX',
  TOGGLE_RECORDING: 'TOGGLE_RECORDING',
  SET_METRIC: 'SET_METRIC',
  ADD_PART: 'ADD_PART',
  REMOVE_PART: 'REMOVE_PART',
  SET_PART_NAME: 'SET_PART_NAME',
  SAVE_PART_RESULT: 'SAVE_PART_RESULT',
  SAVE_PART_NOTES: 'SAVE_PART_NOTES',
};

module.exports = editWorkoutConstants;
