/*
* @Author: vincetam
* @Date:   2016-01-12 12:10:36
* @Last Modified by:   VINCE
* @Last Modified time: 2016-01-18 11:17:49
*/

'use strict';

var modalConstants = {
  OPEN_EDIT_WORKOUT_MODAL: 'OPEN_EDIT_WORKOUT_MODAL',
  CLOSE_EDIT_WORKOUT_MODAL: 'CLOSE_EDIT_WORKOUT_MODAL',
  OPEN_VIEW_WORKOUT_MODAL: 'OPEN_VIEW_WORKOUT_MODAL',
  CLOSE_VIEW_WORKOUT_MODAL: 'CLOSE_VIEW_WORKOUT_MODAL',
  OPEN_INSTRUCTIONS_MODAL: 'OPEN_INSTRUCTIONS_MODAL',
  CLOSE_INSTRUCTIONS_MODAL: 'CLOSE_INSTRUCTIONS_MODAL',
  OPEN_EXERCISE_MODAL: 'OPEN_EXERCISE_MODAL',
  CLOSE_EXERCISE_MODAL: 'CLOSE_EXERCISE_MODAL',
  OPEN_PART_MODAL: 'OPEN_PART_MODAL',
  CLOSE_PART_MODAL: 'CLOSE_PART_MODAL',
  OPEN_DATE_MODAL: 'OPEN_DATE_MODAL',
  CLOSE_DATE_MODAL: 'CLOSE_DATE_MODAL',
  OPEN_LOG_MODAL: 'OPEN_LOG_MODAL',
  CLOSE_LOG_MODAL: 'CLOSE_LOG_MODAL',
};

module.exports = modalConstants;
