'use strict';

var modifyWorkoutConstants = {
  GET_WORKOUT: 'GET_WORKOUT',
  MODIFY_WORKOUT: 'MODIFY_WORKOUT',
  UPDATE_WORKOUT: 'UPDATE_WORKOUT',
  TOGGLE_TIME_EDIT: 'TOGGLE_TIME_EDIT',
  // TOGGLE_REP_EDIT: 'TOGGLE_REP_EDIT',
  SET_EXERCISE_NAME: 'SET_EXERCISE_NAME',
  SET_REPS: 'SET_REPS',
  SET_LOAD: 'SET_LOAD',
  SET_HOLD: 'SET_HOLD',
  SET_DIST: 'SET_DIST',
  SET_DISTUNIT: 'SET_DISTUNIT'
};

module.exports = modifyWorkoutConstants;
